# Generated by Django 3.1.7 on 2021-03-21 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_song_sortinstance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sortinstance',
            name='user',
            field=models.CharField(max_length=50),
        ),
    ]
